model:        Bd_Orm_Main_Genre
page_name:    ジャンル

form:
  sequence:
    column:      sequence
    direction:   ASC
  fields:
    id:
      settings:
        label: ID
    name:
      settings:
        label: タイトル

list:
  delete_label:  削除
  display:
    - label:     ID
      column:    id

    - label:     タイトル
      column:    name

    - label:     スレッド編集
      html:      <a href="/control/thread?group=%record:id%">スレッド編集&nbsp;<i class="icon-chevron-right"></i></a>