model:        Bd_Orm_Main_Thread
page_name:    Thread

navi:
  label: <i class="icon-chevron-left"></i>&nbsp;ジャンルに戻る
  uri:   /control/genre

form:
  fields:

    id:
      settings:
        label: ID

    title:
      settings:
        label: タイトル

    genre_id:
      settings:
        label: ジャンル

    Tag__id:
      settings:
        label: タグ

grouping:
  fixed:
    target:    genre_id
    model:
      name:    Bd_Orm_Main_Genre
      display: name

list:
  filter:        Bd_Scaffold_Filter_Thread
  per_page:      10
  display:
    - label:     ID
      column:    id
      style:     width:60px;

    - label:     タイトル
      column:    title
      style:     width:31%;min-width:200px;

    - label:     ジャンル
      column:    genre.name
      style:     width:120px;

    - label:     登録日時
      column:    created_at
      style:     width:160px;
